#!/usr/bin/python3
# Simple Python CGI test script
import os
import sys

# CGI output headers
print("Content-Type: text/html")
print("X-CGI-Test: Python")
print()  # Empty line separates headers from body

# HTML content
print("<!DOCTYPE html>")
print("<html>")
print("<head><title>Python CGI Test</title></head>")
print("<body>")
print("<h1>Python CGI Test Successful!</h1>")
print("<p>This page was generated by a Python CGI script.</p>")
print("<p><strong>Current Working Directory:</strong> " + os.getcwd() + "</p>")
print("<p><strong>Python Version:</strong> " + sys.version + "</p>")

# Read POST data if available
if os.environ.get('REQUEST_METHOD') == 'POST':
    content_length_str = os.environ.get('CONTENT_LENGTH', '0')
    if content_length_str and content_length_str.isdigit():
        content_length = int(content_length_str)
        if content_length > 0:
            post_data = sys.stdin.read(content_length)
            print("<p><strong>POST Data:</strong> " + post_data + "</p>")

print("</body>")
print("</html>")
