#!/usr/bin/env node

// Simple TypeScript CGI test program
import { execSync } from 'child_process';

function main() {
    try {
        // CGI output headers
        console.log("Content-Type: text/html");
        console.log("X-CGI-Test: TypeScript");
        console.log("");  // Empty line separates headers from body

        // HTML content
        console.log("<!DOCTYPE html>");
        console.log("<html>");
        console.log("<head><title>TypeScript CGI Test</title></head>");
        console.log("<body>");
        console.log("<h1>TypeScript CGI Test Successful!</h1>");
        console.log("<p>This page was generated by a TypeScript CGI handler.</p>");

        // Display current time
        const now = new Date();
        console.log(`<p><strong>Current Time:</strong> ${now.toString()}</p>`);

        console.log("</body>");
        console.log("</html>");

    } catch (error) {
        // Error handling
        console.log("Content-Type: text/html");
        console.log("Status: 500 Internal Server Error");
        console.log("");
        console.log("<!DOCTYPE html>");
        console.log("<html><body>");
        console.log("<h1>CGI Error</h1>");
        console.log(`<p>Error: ${error}</p>`);
        console.log("</body></html>");
    }
}

main();
